In [1]:
import numpy as np 
import tensorflow as tf 
from tensorflow import keras 
from keras import Sequential 
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten

2024-11-11 19:59:47.152314: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-11-11 19:59:48.701516: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-11-11 19:59:50.916471: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:

train_ds = keras.utils.image_dataset_from_directory(
    directory = 'data/train_ds',
    labels = 'inferred',
    label_mode = 'int',
    batch_size = 32,
    image_size = (256,256)
)

validation_ds = keras.utils.image_dataset_from_directory(
    directory = 'data/test_ds',
    labels = 'inferred',
    label_mode = 'int',
    batch_size = 32,
    image_size = (256,256)
)

Found 238 files belonging to 2 classes.
Found 61 files belonging to 2 classes.


In [3]:
# Normilize the image
def process(image, label):
    image = tf.cast(image/255, tf.float32)
    return image, label 

train_ds = train_ds.map(process)
validation_ds = validation_ds.map(process)



In [4]:
model = Sequential()
model.add(Conv2D(32, kernel_size = (3,3), padding = 'valid', activation = 'relu', input_shape = (256,256,3)))

model = Sequential()

model.add(Conv2D(32, kernel_size = (3,3), padding = 'valid', activation = 'relu', input_shape = (256,256,3)))
model.add(MaxPooling2D(pool_size = (2,2), strides = 2, padding = 'valid'))

model.add(Conv2D(64, kernel_size = (3,3), padding = 'valid', activation = 'relu'))
model.add(MaxPooling2D(pool_size = (2,2), strides = 2, padding = 'valid'))

model.add(Conv2D(128, kernel_size = (3,3), padding = 'valid', activation = 'relu'))
model.add(MaxPooling2D(pool_size = (2,2), strides = 2, padding = 'valid'))

model.add(Flatten())
model.add(Dense(128,activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_1 (Conv2D)           (None, 254, 254, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2  (None, 127, 127, 32)      0         
 D)                                                              
                                                                 
 conv2d_2 (Conv2D)           (None, 125, 125, 64)      18496     
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 62, 62, 64)        0         
 g2D)                                                            
                                                                 


2024-11-11 19:59:56.267035: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 58982400 exceeds 10% of free system memory.
2024-11-11 19:59:56.330827: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 58982400 exceeds 10% of free system memory.
2024-11-11 19:59:56.367973: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 58982400 exceeds 10% of free system memory.


 conv2d_3 (Conv2D)           (None, 60, 60, 128)       73856     
                                                                 
 max_pooling2d_2 (MaxPoolin  (None, 30, 30, 128)       0         
 g2D)                                                            
                                                                 
 flatten (Flatten)           (None, 115200)            0         
                                                                 
 dense (Dense)               (None, 128)               14745728  
                                                                 
 dense_1 (Dense)             (None, 64)                8256      
                                                                 
 dense_2 (Dense)             (None, 1)                 65        
                                                                 
Total params: 14847297 (56.64 MB)
Trainable params: 14847297 (56.64 MB)
Non-trainable params: 0 (0.00 Byte)
__________________________________

In [5]:
model.compile(optimizer='adam', loss='binary_crossentropy',metrics = ['accuracy'])

In [6]:
history = model.fit(train_ds, epochs=15, validation_data= validation_ds)


Epoch 1/15


2024-11-11 19:59:56.983430: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 58982400 exceeds 10% of free system memory.
2024-11-11 19:59:57.010105: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 58982400 exceeds 10% of free system memory.


8/8 [==============================] - 39s 4s/step - loss: 1.3799 - accuracy: 0.5168 - val_loss: 0.7923 - val_accuracy: 0.5410
Epoch 2/15
8/8 [==============================] - 38s 4s/step - loss: 0.7078 - accuracy: 0.5378 - val_loss: 0.6630 - val_accuracy: 0.5410
Epoch 3/15
8/8 [==============================] - 38s 5s/step - loss: 0.6096 - accuracy: 0.6975 - val_loss: 0.6557 - val_accuracy: 0.5738
Epoch 4/15
8/8 [==============================] - 40s 5s/step - loss: 0.5695 - accuracy: 0.6681 - val_loss: 0.6944 - val_accuracy: 0.5574
Epoch 5/15
8/8 [==============================] - 33s 4s/step - loss: 0.5340 - accuracy: 0.7185 - val_loss: 0.5044 - val_accuracy: 0.7541
Epoch 6/15
8/8 [==============================] - 28s 3s/step - loss: 0.3166 - accuracy: 0.8992 - val_loss: 0.4947 - val_accuracy: 0.7869
Epoch 7/15
8/8 [==============================] - 28s 3s/step - loss: 0.2602 - accuracy: 0.8655 - val_loss: 0.4674 - val_accuracy: 0.7541
Epoch 8/15
8/8 [=============================

In [7]:
# 0 - No traffic 
# 1 - traffic 

In [13]:
model.save('traffic_dector_main.h5')

In [19]:
# 1.Normal
# 0.AD
import cv2 
testimg = cv2.imread('traffictest.jpeg')
# plt.imshow(testimg)
testimg = cv2.resize(testimg,(256,256))
testinput = testimg.reshape((1,256,256,3))
model.predict(testinput)

1/1 [==============================] - 0s 73ms/step


array([[1.]], dtype=float32)

In [20]:
# 1.Normal
# 0.AD
import cv2 
testimg = cv2.imread('clearroads.jpeg')
# plt.imshow(testimg)
testimg = cv2.resize(testimg,(256,256))
testinput = testimg.reshape((1,256,256,3))
model.predict(testinput)

1/1 [==============================] - 0s 60ms/step


array([[0.]], dtype=float32)

In [17]:
# 1.Normal
# 0.AD
import cv2 
testimg = cv2.imread('cr2.jpeg')
# plt.imshow(testimg)
testimg = cv2.resize(testimg,(256,256))
testinput = testimg.reshape((1,256,256,3))
model.predict(testinput)

1/1 [==============================] - 0s 52ms/step


array([[0.]], dtype=float32)

In [18]:
# 1.Normal
# 0.AD
import cv2 
testimg = cv2.imread('notraffic1.jpeg')
# plt.imshow(testimg)
testimg = cv2.resize(testimg,(256,256))
testinput = testimg.reshape((1,256,256,3))
model.predict(testinput)

1/1 [==============================] - 0s 71ms/step


array([[0.]], dtype=float32)

In [24]:
# 1.Normal
# 0.AD
import cv2 
testimg = cv2.imread('testimg1.jpeg')
# plt.imshow(testimg)
testimg = cv2.resize(testimg,(256,256))
testinput = testimg.reshape((1,256,256,3))
model.predict(testinput)

1/1 [==============================] - 0s 52ms/step


array([[1.]], dtype=float32)

In [23]:
# 1.Normal
# 0.AD
import cv2 
testimg = cv2.imread('notraffic1.jpeg')
# plt.imshow(testimg)
testimg = cv2.resize(testimg,(256,256))
testinput = testimg.reshape((1,256,256,3))
model.predict(testinput)

1/1 [==============================] - 0s 130ms/step


array([[0.]], dtype=float32)